#!/bin/bash
set -eu

print_color() {
    printf "\e[%bm%b\e[0m\n" "$1" "$2"
}

# Directory to look for bootstrap executables in
BOOTSTRAP_D="${BASH_SOURCE[0]}.d"

print_color "32" "STARTING SYSTEM BOOTSTRAPPING\n"

if [ -f "$HOME/.zshenv" ]; then
    print_color "32" "Loading environment variables from $HOME/.zshenv"
    export $(echo $(cat $HOME/.zshenv | sed 's/#.*//g'| xargs) | envsubst)
fi

if [[ ! -d "$BOOTSTRAP_D" ]]; then
    echo "Error: bootstrap directory '$BOOTSTRAP_D' not found" >&2
    exit 1
fi

print_color "32" "\nRunning bootstrapping scripts"
find "$BOOTSTRAP_D" -type f | sort | while IFS= read -r bootstrap; do
    if [[ -x "$bootstrap" && ! "$bootstrap" =~ "##" && ! "$bootstrap" =~ "~$" ]]; then
        if ! "$bootstrap"; then
            echo "Error: bootstrap '$bootstrap' failed" >&2
            exit 1
        fi
    fi
done

if [[ -d $XDG_CONFIG_HOME/custom/bootstrap ]]; then
    print_color "32" "\nRunning custom bootstrapping scripts"
    find "$XDG_CONFIG_HOME/custom/bootstrap" -type f | sort | while IFS= read -r bootstrap; do
        if [[ -x "$bootstrap" && ! "$bootstrap" =~ "##" && ! "$bootstrap" =~ "~$" ]]; then
            if ! "$bootstrap"; then
                echo "Error: custom bootstrap '$bootstrap' failed" >&2
                exit 1
            fi
        fi
    done
else
    print_color "32" "\nNo custom bootstrapping scripts to run"
fi

# Finished bootstrapping with yadm
print_color "32" "\nSYSTEM BOOTSTRAPPING COMPLETE"
