#!/bin/sh

# Setup OS specific configuration

echo "Setting OS specific configuration"

system_type=$(uname -s)

if [ $system_type = "Darwin" ]; then
  # REMEMBER TO CHANGE VERSION IF THE CONFIGURATION IS CHANGED IN ANYWAY
  group=sawle.setup
  property=ConfigVersion
  configVersion=1

  # This stops the Dock and Finder being killed if nothing has been changed
  if [[ $(defaults read $group $property) -ne configVersion ]]; then
    echo MacOS configuration is outdated, updating to version $configVersion

    # Configure dock
    defaults write com.apple.dock autohide -bool true
    defaults write com.apple.dock "autohide-time-modifier" -float "1.5" 
    defaults write com.apple.dock "autohide-delay" -float "0"
    killall Dock

    # Configure trackpad
    defaults write -globalDomain com.apple.swipescrolldirection -bool false

    # Empty bin items after 30 days
    defaults write com.apple.finder "FXRemoveOldTrashItems" -bool "true"
    killall Finder

    # Configure iTerm2 to use configuration from .config
    defaults write com.googlecode.iterm2 PrefsCustomFolder -string "$XDG_CONFIG_HOME/iterm2"
    defaults write com.googlecode.iterm2 LoadPrefsFromCustomFolder -bool true

    defaults write $group $property -int $configVersion
  fi
fi
