#!/bin/sh

# Install applications using OS specific package manager
# Future bootstrapping steps can assume that these
# applications are installed

system_type=$(uname -s)

if [ $system_type = "Darwin" ]; then
  source "$XDG_CONFIG_HOME/homebrew/homebrew.zsh"

  # Install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  createBrewfile
  bbi
elif [ $system_type = "Linux" ]; then
  sudo pacman -Syu starship

  // 1Password gpg key
  gpg --receive-keys 3FEF9748469ADBE15DA7CA80AC2D62742012EA22
  
  yay -Syu 1password 1password-cli code discord slack zplug
fi