#!/bin/sh

install_gem () {
  if ! gem list --local | grep -q $1; then
    echo "Installing $1"
    sudo gem install $1
  fi
}

# Install applications using OS specific package manager
# Future bootstrapping steps can assume that these
# applications are installed

system_type=$(uname -s)

if [ $system_type = "Darwin" ]; then
  source "$XDG_CONFIG_HOME/homebrew/homebrew.zsh"

  # Install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  echo "Installing homebrew packages"
  bbi
fi

install_gem colorls