#!/bin/sh

# Alias config files that can not be stored with $XDG_CONFIG_HOME to their respective locations
echo "\nAlias distributed configuration files"

system_type=$(uname -s)

# VS Code
rm ~/Library/Application\ Support/Code/User/settings.json
ln -s $XDG_CONFIG_HOME/code/settings.json ~/Library/Application\ Support/Code/User/settings.json

if [ $system_type = "Darwin" ]; then
  # Setup 1Password CLI SSH auth sock to be referenced when wishing to use SSH keys stored in 1Password
  if [[ ! -e "$XDG_CONFIG_HOME/1password/agent.sock" ]]; then
    if [ ! -d "$XDG_CONFIG_HOME/1password" ]; then
      mkdir -p "$XDG_CONFIG_HOME/1password"
    fi

    ln -s ~/Library/Group\ Containers/2BUA8C4S2C.com.1password/t/agent.sock $XDG_CONFIG_HOME/1password/agent.sock
  fi
fi